# Use root to login
ansible_user: root

# Deploy Origin - upstream version
deployment_type: origin

# Use password-based authentication
openshift_master_identity_providers:
- name: htpasswd_provider
  challenge: true
  login: true
  kind: HTPasswdPasswordIdentityProvider
# Prehashed version of 'redhat' password, see http://www.htaccesstools.com/htpasswd-generator/
openshift_master_htpasswd_users:
  admin: '$apr1$jdI7FA/q$q.1ym4Pno9IAsD19Dcq.n0'

# Machines don't have sufficient RAM - skip this check
openshift_disable_check: memory_availability

# Enable firewalld
os_firewall_enabled: true
os_firewall_use_firewalld: true

# Use custom subdomain
openshift_hosted_router_force_subdomain: 147.229.13.61.xip.io

# Masters should act as infra nodes and workers
openshift_node_groups:
- name: node-config-master
  labels:
    - 'node-role.kubernetes.io/master=true'
    - 'node-role.kubernetes.io/infra=true'
    - 'node-role.kubernetes.io/compute=true'
  edits:
    - key: kubeletArguments.feature-gates
      value:
        - RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true,PersistentLocalVolumes=true
    - key: kubeletArguments.max-pods
      value:
        - '250'
    - key: kubeletArguments.image-gc-high-threshold
      value:
        - '90'
    - key: kubeletArguments.image-gc-low-threshold
      value:
        - '50'
    - key: kubeletArguments.minimum-container-ttl-duration
      value:
        - '10m'
    - key: kubeletArguments.maximum-dead-containers
      value:
        - '50'
    - key: kubeletArguments.kube-reserved
      value:
        - 'cpu=100m'
